### ISSUE TITLE
关于sm9曲线参数设置

### ISSUE THREAD

**Issue by YLINR** [xlcetc/cryptogm#4]
sm9curve包里更改了原bn256包中的多个参数，请问这些参数是怎么计算出来的？
我去比对了sm9的文档中指定的参数，只对上了order和p，那么其余参数是怎么得出的，能否提供些学习资料，谢谢！

**Comment by triplewz** [comment]
参数主要用于优化BN256曲线计算的，生成方式可以参考genconst里面的代码，具体原理可以参考使用的地方，有一些写在注释里了，有一些也标出了论文出处，可以参考

**Comment by YLINR** [comment]
> 参数主要用于优化BN256曲线计算的，生成方式可以参考genconst里面的代码，具体原理可以参考使用的地方，有一些写在注释里了，有一些也标出了论文出处，可以参考
谢谢。
请问这个b的值是怎么来的？
![image](https://user-images.githubusercontent.com/61904283/171638134-8489cad4-698f-46c8-9239-a8d2e1a7728a.png)

**Comment by YLINR** [comment]
![image](https://user-images.githubusercontent.com/61904283/171639931-ec5413dd-5b65-4bd8-8904-9b2dad8dfda0.png)
还有这里，上述值跟sm9文档中的G2是有什么关系？
![image](https://user-images.githubusercontent.com/61904283/171640248-d90accbd-7c75-478d-84bd-831aed076433.png)
麻烦您再解答一下，谢谢，辛苦了

**Comment by triplewz** [comment]
> > 参数主要用于优化BN256曲线计算的，生成方式可以参考genconst里面的代码，具体原理可以参考使用的地方，有一些写在注释里了，有一些也标出了论文出处，可以参考
> > 谢谢。
> > 请问这个b的值是怎么来的？
> > ![image](https://user-images.githubusercontent.com/61904283/171638134-8489cad4-698f-46c8-9239-a8d2e1a7728a.png)
b是-1/2的蒙哥马利表示方法，是sm9扩域的参数吧
![image](https://user-images.githubusercontent.com/26701280/171641726-c2cb495d-d110-4b79-ab9d-47f2820d7710.png)

**Comment by triplewz** [comment]
上面的G2生成元也是sm9G2生成元的蒙哥马利表示方法

**Comment by YLINR** [comment]
![image](https://user-images.githubusercontent.com/61904283/171789970-5b50c462-c88d-44d1-9489-3ca8967473e2.png)
啊我没有表达清楚，我主要是想知道这串参数是从哪个文档获得的？我在国密9的标准文档中好像没有看到。
顺便祝您端午安康~

**Comment by triplewz** [comment]
这个值是要选择一个Fp2里面的非平方根和非立方根，sm9确实没有给具体值，但是-1/2i是满足的

**Comment by YLINR** [comment]
> 这个值是要选择一个Fp2里面的非平方根和非立方根，sm9确实没有给具体值，但是-1/2i是满足的

这个值是出自哪个文献？

**Comment by triplewz** [comment]
sm9里面的描述：
![image](https://user-images.githubusercontent.com/26701280/172055154-395d9a72-63b9-4f67-9702-dab116a45ff6.png)
[bn256论文](http://cryptojedi.org/papers/dclxvi-20100714.pdf)的描述：
![image](https://user-images.githubusercontent.com/26701280/172055177-d13527b5-79e2-4d61-aa8b-0e4607fda716.png)

**Comment by YLINR** [comment]
好的谢谢
再问一下，这个变量的数据是怎么得来的？
![image](https://user-images.githubusercontent.com/61904283/172155015-36abc7c3-f214-4de5-bfaa-7669070c5335.png)

**Comment by YLINR** [comment]
![image](https://user-images.githubusercontent.com/61904283/172180268-7c65fd9a-9cf8-4220-937b-88ad446bfd76.png)
pminusone是指p-1吗？为什么值与p-2相差那么大

**Comment by triplewz** [comment]
> 好的谢谢 再问一下，这个变量的数据是怎么得来的？ ![image](https://user-images.githubusercontent.com/61904283/172155015-36abc7c3-f214-4de5-bfaa-7669070c5335.png)

根据G1和G2生成元计算一次pairing就可以了

**Comment by triplewz** [comment]
> ![image](https://user-images.githubusercontent.com/61904283/172180268-7c65fd9a-9cf8-4220-937b-88ad446bfd76.png) pminusone是指p-1吗？为什么值与p-2相差那么大

pMinus1应该是蒙哥马利表示方法

**Comment by YLINR** [comment]
好的谢谢!!

**Comment by YLINR** [comment]
不好意思哈，再打扰一下。
![image](https://user-images.githubusercontent.com/61904283/172639673-941a977f-c05a-477b-acca-cd7051efdda8.png)
用genconsts.go生成的结果跟您在constant.go里定义的数值不同是怎么回事？以哪个为准

**Comment by YLINR** [comment]
![image](https://user-images.githubusercontent.com/61904283/172803567-5038c363-2f53-4503-b180-178cc1d32e8a.png)
s的定义中sqrt(-3)，怎么用程序实现。依然使用math/big包吗

**Comment by YLINR** [comment]
> ![image](https://user-images.githubusercontent.com/61904283/172803567-5038c363-2f53-4503-b180-178cc1d32e8a.png) s的定义中sqrt(-3)，怎么用程序实现。依然使用math/big包吗

我运行了您在bn256_test中写的genS的过程，但结果没有跟constant.go中s 的值对上。所以希望您详细的讲解一下sqrt(-3)，怎么用程序实现

**Comment by triplewz** [comment]
参考sm9c1.4里面的有限域求平方根：
![image](https://user-images.githubusercontent.com/26701280/174418077-eb516ebe-7ba6-4339-9aad-f80e2df310f1.png)
bn256_test s应该是把ss从蒙哥马利表示方法decode一下，里面有些值测试临时使用的，ss值：
`9daaaaaaae2f89472af8f15476909b18298c464234e93cfdc94cedfd9c1b1fc`
表示成gfp形式：
`gfP{0xdc94cedfd9c1b1fc, 0x8298c464234e93cf, 0x72af8f15476909b1, 0x9daaaaaaae2f8942`。

**Comment by triplewz** [comment]
> 不好意思哈，再打扰一下。
> ![image](https://user-images.githubusercontent.com/61904283/172639673-941a977f-c05a-477b-acca-cd7051efdda8.png)
> 用genconsts.go生成的结果跟您在constant.go里定义的数值不同是怎么回事？以哪个为准

以constant.go中的值为准，genconsts.go打印`xi`的值的时候改变了原来的值，已经修改。

**Comment by YLINR** [comment]
好的谢谢。
请问您知道hid  也就是签名函数中提到的签名私钥生成函数识别符是什么吗？为什么设置为0x01呢

**Comment by triplewz** [comment]
这个其实没有确定值，sm9里给的说明是`用一个字节表示的私钥生成函数识别符，由 KGC 选择并公开`。
但是sm9给的例子里，签名算法用的是1，密钥交换用的是2，密钥封装和公钥加密用的是3，所以测试用例里参考例子的值。

**Comment by YLINR** [comment]
> 

所以是不是hid的取值可以是任意数值，只要可以用一个字节表示。

**Comment by triplewz** [comment]
按定义确实是这样

**Comment by YLINR** [comment]
好的谢谢！
